-- ============================================================
-- Data Quality Monitoring
-- ============================================================

GRANT EXECUTE DATA METRIC FUNCTION ON ACCOUNT TO ROLE ACCOUNTADMIN;

-- NULL_COUNT checks on Bronze tables
ALTER TABLE ENERGY_MARKET.BRONZE.GRID_GENERATION_RAW
ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT
ON (VALUE_MWH);

ALTER TABLE ENERGY_MARKET.BRONZE.GRID_LOAD_RAW
ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT
ON (VALUE_MWH);

ALTER TABLE ENERGY_MARKET.BRONZE.WEATHER_RAW
ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT
ON (TEMPERATURE_2M);

-- ROW_COUNT checks on Bronze tables
ALTER TABLE ENERGY_MARKET.BRONZE.GRID_GENERATION_RAW
ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.ROW_COUNT ON ();

ALTER TABLE ENERGY_MARKET.BRONZE.GRID_LOAD_RAW
ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.ROW_COUNT ON ();

ALTER TABLE ENERGY_MARKET.BRONZE.WEATHER_RAW
ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.ROW_COUNT ON ();

-- Schedule: run every 60 minutes
ALTER TABLE ENERGY_MARKET.BRONZE.GRID_GENERATION_RAW
SET DATA_METRIC_SCHEDULE = '60 MINUTE';

ALTER TABLE ENERGY_MARKET.BRONZE.GRID_LOAD_RAW
SET DATA_METRIC_SCHEDULE = '60 MINUTE';

ALTER TABLE ENERGY_MARKET.BRONZE.WEATHER_RAW
SET DATA_METRIC_SCHEDULE = '60 MINUTE';
