
CREATE OR REPLACE DYNAMIC TABLE ENERGY_MARKET.GOLD.ENERGY_WEATHER_HOURLY
TARGET_LAG = '1 hour'
WAREHOUSE = ENERGY_WH
AS
WITH generation_pivoted AS (
    SELECT
        TIMESTAMP_UTC,
        SUM(VALUE_MWH) AS TOTAL_GENERATION_MWH,
        SUM(CASE WHEN ENERGY_CLASS = 'Renewable' THEN VALUE_MWH ELSE 0 END) AS RENEWABLE_MWH,
        SUM(CASE WHEN ENERGY_CLASS = 'Conventional' THEN VALUE_MWH ELSE 0 END) AS CONVENTIONAL_MWH,
        SUM(CASE WHEN FILTER_NAME = 'Wind Onshore' THEN VALUE_MWH ELSE 0 END) AS WIND_ONSHORE_MWH,
        SUM(CASE WHEN FILTER_NAME = 'Wind Offshore' THEN VALUE_MWH ELSE 0 END) AS WIND_OFFSHORE_MWH,
        SUM(CASE WHEN FILTER_NAME = 'Photovoltaik' THEN VALUE_MWH ELSE 0 END) AS SOLAR_MWH,
        SUM(CASE WHEN FILTER_NAME = 'Braunkohle' THEN VALUE_MWH ELSE 0 END) AS LIGNITE_MWH,
        SUM(CASE WHEN FILTER_NAME = 'Erdgas' THEN VALUE_MWH ELSE 0 END) AS GAS_MWH
    FROM ENERGY_MARKET.SILVER.GRID_GENERATION_CLEAN
    GROUP BY TIMESTAMP_UTC
),
load_data AS (
    SELECT
        TIMESTAMP_UTC,
        MAX(CASE WHEN FILTER_NAME = 'Stromverbrauch Gesamt' THEN VALUE_MWH END) AS TOTAL_LOAD_MWH
    FROM ENERGY_MARKET.SILVER.GRID_LOAD_CLEAN
    GROUP BY TIMESTAMP_UTC
),
weather_avg AS (
    SELECT
        TIMESTAMP_UTC,
        AVG(TEMPERATURE_2M)      AS AVG_TEMPERATURE,
        AVG(WIND_SPEED_10M)      AS AVG_WIND_SPEED,
        AVG(SHORTWAVE_RADIATION) AS AVG_SOLAR_RADIATION,
        AVG(CLOUD_COVER)         AS AVG_CLOUD_COVER,
        AVG(PRECIPITATION)       AS AVG_PRECIPITATION
    FROM ENERGY_MARKET.SILVER.WEATHER_CLEAN
    GROUP BY TIMESTAMP_UTC
)
SELECT
    g.TIMESTAMP_UTC,
    g.TOTAL_GENERATION_MWH,
    g.RENEWABLE_MWH,
    g.CONVENTIONAL_MWH,
    g.WIND_ONSHORE_MWH,
    g.WIND_OFFSHORE_MWH,
    g.SOLAR_MWH,
    g.LIGNITE_MWH,
    g.GAS_MWH,
    l.TOTAL_LOAD_MWH,
    ROUND(g.RENEWABLE_MWH / NULLIF(g.TOTAL_GENERATION_MWH, 0) * 100, 2) AS RENEWABLE_SHARE_PCT,
    ROUND(g.TOTAL_GENERATION_MWH - NULLIF(l.TOTAL_LOAD_MWH, 0), 2)      AS GENERATION_LOAD_DELTA_MWH,
    w.AVG_TEMPERATURE,
    w.AVG_WIND_SPEED,
    w.AVG_SOLAR_RADIATION,
    w.AVG_CLOUD_COVER,
    w.AVG_PRECIPITATION,
    CASE
        WHEN ROUND(g.TOTAL_GENERATION_MWH - NULLIF(l.TOTAL_LOAD_MWH,0), 2) < -2000 THEN 'Critical'
        WHEN ROUND(g.TOTAL_GENERATION_MWH - NULLIF(l.TOTAL_LOAD_MWH,0), 2) < 0     THEN 'Tight'
        WHEN ROUND(g.TOTAL_GENERATION_MWH - NULLIF(l.TOTAL_LOAD_MWH,0), 2) < 2000  THEN 'Balanced'
        ELSE 'Surplus'
    END AS GRID_STATUS
FROM generation_pivoted g
LEFT JOIN load_data l ON g.TIMESTAMP_UTC = l.TIMESTAMP_UTC
LEFT JOIN weather_avg w ON g.TIMESTAMP_UTC = w.TIMESTAMP_UTC;
