
CREATE OR REPLACE DYNAMIC TABLE ENERGY_MARKET.SILVER.GRID_GENERATION_CLEAN
TARGET_LAG = '1 hour'
WAREHOUSE = ENERGY_WH
AS
SELECT
    RECORD_ID,
    FILTER_ID,
    FILTER_NAME,
    REGION,
    RESOLUTION,
    TIMESTAMP_UTC,
    VALUE_MWH,
    INGESTED_AT,
    CASE
        WHEN FILTER_NAME IN ('Wind Onshore','Wind Offshore','Photovoltaik','Biomasse','Wasserkraft','Sonstige Erneuerbare')
        THEN 'Renewable'
        ELSE 'Conventional'
    END AS ENERGY_CLASS
FROM ENERGY_MARKET.BRONZE.GRID_GENERATION_RAW
WHERE VALUE_MWH IS NOT NULL
  AND VALUE_MWH >= 0
  AND TIMESTAMP_UTC IS NOT NULL;

CREATE OR REPLACE DYNAMIC TABLE ENERGY_MARKET.SILVER.GRID_LOAD_CLEAN
TARGET_LAG = '1 hour'
WAREHOUSE = ENERGY_WH
AS
SELECT
    RECORD_ID,
    FILTER_ID,
    FILTER_NAME,
    REGION,
    RESOLUTION,
    TIMESTAMP_UTC,
    VALUE_MWH,
    INGESTED_AT
FROM ENERGY_MARKET.BRONZE.GRID_LOAD_RAW
WHERE VALUE_MWH IS NOT NULL
  AND VALUE_MWH > 0
  AND TIMESTAMP_UTC IS NOT NULL;

CREATE OR REPLACE DYNAMIC TABLE ENERGY_MARKET.SILVER.WEATHER_CLEAN
TARGET_LAG = '1 hour'
WAREHOUSE = ENERGY_WH
AS
SELECT
    RECORD_ID,
    LOCATION_NAME,
    LATITUDE,
    LONGITUDE,
    TIMESTAMP_UTC,
    TEMPERATURE_2M,
    WIND_SPEED_10M,
    WIND_DIRECTION_10M,
    SHORTWAVE_RADIATION,
    CLOUD_COVER,
    PRECIPITATION,
    INGESTED_AT
FROM ENERGY_MARKET.BRONZE.WEATHER_RAW
WHERE TIMESTAMP_UTC IS NOT NULL
  AND TEMPERATURE_2M IS NOT NULL
  AND WIND_SPEED_10M >= 0;
